### ISSUE TITLE
报错，按照你的步骤还需什么？

### ISSUE THREAD

**Issue by wsdo** [Aaaaaaaty/vue-im#2]
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./server/bin/www`
module.js:472
    throw err;
    ^

Error: Cannot find module 'morgan'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wangshudong/item/vue-im/server/app.js:5:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Aaaaaaaty** [comment]
已更新readme
